services:
              - docker


before_install:
                - docker build -t sheshadrin/docker-react -f Dockerfile.dev .

script:
             - docker run sheshadrin/docker-react npm run test -- --coverage

